# -*- coding: utf-8 -*-
"""[TP1] procesamiento de archivos PDF

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1p6euNo-hwhPiQm2La8EgScYWWESWEg_Z

# **TP1 Procesamiento de archivos PDF**

**Alumno:** Finocchio, David Alejandro

**Profesora:** Diedrichs, Ana Laura

1. Adquisición y metadatos
Descarga: Utilizando las librerías requests o urllib, descarga un archivo PDF desde un enlace público (por ejemplo, un artículo científico de arXiv o un reporte institucional). No puede usar el mismo pdf o enlace que otra persona ya haya presentado en el foro.

    Inspección: Muestra por pantalla los metadatos del archivo: título, autor, número de páginas y software de creación.

    Sugerencia: Puedes utilizar librerías como PyMuPDF (fitz) o PyPDF2.
"""

!pip install PyMuPDF

#Importar librerías
import fitz
import requests

url = "https://repositorio.cepal.org/server/api/core/bitstreams/f15588e0-d926-4821-869e-46143f1692e2/content"

filename = 'CEPAL147.pdf'

try:
  response = requests.get(url, stream=True)
  response.raise_for_status()

  #Abrimos el archivo
  with open(filename, 'wb') as f:
    f.write(response.content)
  #Verificamos la ejecución
  print(f"PDF downloaded successfully to {filename}")
except requests.exceptions.RequestException as e:
  print(f"Error downloading PDF: {e}")
except Exception as e:
  print(f"An unexpected error occurred: {e}")

#Abrimos el archivo con la librería PyMuPDF
doc = fitz.open("CEPAL147.pdf")
#Extraemos los metadatos
doc.metadata

"""2. Análisis estructural del texto
Extracción cruda: Extrae el texto completo de las primeras 5 páginas. Identifica la función de la librería elegida que te ayuda en esta tarea y te permite ver el texto extraído lo más crudo posible.

    Análisis de separadores: Observa y describe cómo están separados los párrafos, las secciones y los capítulos.

    Identificación de caracteres: ¿Qué caracteres especiales funcionan como separadores de línea o de bloque en este archivo específico? (Ej: \n, \r, \t o secuencias de espacios).
"""

#Verificar que el doc tenga 5 páginas o más
if len(doc) >= 5:
  print(f"El PDF tiene {len(doc)} páginas")
else:
  print("El PDF no cumple con el requisito 5 >= páginas")

#Extraer las 5 primeras páginas del pdf
for n, page in enumerate(doc[:5]):
  print(page.get_text())

"""2. En este texto se utiliza \n como separador principal.

3. Extracción de datos tabulares
Busca una página en el PDF que contenga una tabla de datos.

    Extrae dicha tabla y conviértela en un DataFrame de Pandas.

    Realiza una limpieza básica de la tabla (nombrar columnas, eliminar filas vacías).

    Sugerencia: Se recomienda el uso de pdfplumber o tabula-py.
"""

!pip install tabula-py pandas

import tabula
import pandas as pd

# Leer PDF
tablas = tabula.read_pdf("CEPAL147.pdf", pages='23', stream=True)

df = tablas[0]

# 1. Eliminar filas vacías
df = df.dropna(how='all').reset_index(drop=True)

# 2. Renombrar columnas correctamente
df.columns = ["raw", "Media", "Desv", "Min", "25%", "Mediana", "75%", "Max"]

# 3. Separar Variable y n
df[["Variable", "n"]] = df["raw"].str.extract(r"(.+?)\s(\d+)$")

# 4. Eliminar columna original
df.drop(columns=["raw"], inplace=True)

# 5. Unir filas partidas
df["Variable"] = df["Variable"].astype(str).replace('nan', '')

rows_to_drop = []

for i in range(1, len(df)):
    if pd.isna(df.loc[i, "n"]):
        df.loc[i-1, "Variable"] = df.loc[i-1, "Variable"] + " " + str(df.loc[i, "Variable"])
        rows_to_drop.append(i)

df = df.drop(rows_to_drop).reset_index(drop=True)

# 6. Reordenar columnas
df = df[["Variable", "n", "Media", "Desv", "Min", "25%", "Mediana", "75%", "Max"]]

# 7. Limpiar strings numéricos
df = df.replace({",": ".", " ": ""}, regex=True)

print(df.head())

# 8. Guardar
df.to_csv("tabla_limpia.csv", index=False)

"""4. Análisis de frecuencias (NLP básico)
Elige una página que contenga únicamente texto narrativo, usa la biblioteca nltk o spacy  y realiza lo siguiente:

    Tokenización: Extrae el texto y conviértelo a minúsculas.

    Limpieza: Elimina las stop words (palabras funcionales sin peso semántico como "el", "de", "y") y signos de puntuación.

    Visualización: Genera un gráfico de barras que muestre las 15 palabras más frecuentes en esa página. ¿ Te surgieron en esta visualización tokens que también considerarías stop words? Comenta y justifica.
"""

texto_nlp = doc[17].get_text()
#Convertir a minúsculas
texto_nlp = texto_nlp.lower()
print(texto_nlp)

# Instalar y cargar spaCy (ejecutar una sola vez)
!pip install spacy
!python -m spacy download es_core_news_sm

import spacy
from collections import Counter
import matplotlib.pyplot as plt

# Cargar modelo
nlp = spacy.load("es_core_news_sm")

# Procesar texto
doc = nlp(texto_nlp)

# Limpiar tokens
tokens = [t.lemma_.lower() for t in doc if not t.is_stop and t.is_alpha]

# Contar frecuencias directamente
freq = Counter(tokens)

# Obtener las 15 palabras más frecuentes
top = freq.most_common(15)

# Separar palabras y frecuencias
words = [w for w, f in top]
values = [f for w, f in top]

# Graficar
plt.figure(figsize=(8,5))
plt.bar(words, values)
plt.xticks(rotation=45)
plt.title("15 palabras más frecuentes")
plt.xlabel("Palabras")
plt.ylabel("Frecuencia")
plt.tight_layout()
plt.show()

"""4. Por lo que vemos en el gráfico, si hay algunas palabras que podrían considerarse Stop Words, tales como acceso o recursos. Obviamente, siempre las stops words van a estar dadas por el contexto, por lo que no en todos los textos analizaremos las mismas. Este gráfico también demuestra porque es tan importante calcular la importancia de cada palabra, y no solo la frecuencia.

https://github.com/anadiedrichs/procesamientoDelHabla/blob/main/0_archivos_pdf.ipynb

https://pymupdf.readthedocs.io/en/latest/app1.html

https://sematext.com/blog/entity-extraction-with-spacy/

https://medium.com/@marisr2844/from-messy-to-meaningful-the-magic-of-text-cleaning-with-spacy-404278ce16e8

Gemini Asistente (Incrustado en Collab)
"""